name: Django CI

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

env:
  SECRET_KEY: yoursecretkey
  DEBUG: True
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
  DATABASE_PASS: postgres
  DATABASE_HOST: localhost

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: food
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: |
        cd backend
        python manage.py makemigrations
        python manage.py migrate
    - name: Lint with flake8
      run: |
        cd backend
        flake8
    - name: Run Tests
      run: |
        cd backend
        python manage.py test