name: React CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          cd frontend
          npm install
      - name: Run Tests
        run: |
          cd frontend
          npm run test
